events {
    worker_connections 1024;
}

http {
    upstream reservation_apps {
        server app-1:8080;
        server app-2:8080;
        server app-3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://reservation_apps;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
